apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xndnesh88-nodejs 
  janus-idp.io/tekton: xndnesh88-nodejs
  backstage.io/kubernetes-id: xndnesh88-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xndnesh88-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  