apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xndnesh88-nodejs-gitops
  description: This is GitOps manifest for xndnesh88-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: xndnesh88-nodejs
    backstage.io/kubernetes-id: xndnesh88-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xndnesh88-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xndnesh88-nodejs
